{% set name = "PyCondor" %}
{% set version = "0.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 3424b8f51ac63a18d3c12e1dae5316a5faa0c1dd1606bb6c1f524df5c031fcb5

build:
  entry_points:
    - pycondor = pycondor.cli:cli
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=2.7
    - setuptools >=38.6.0
  run:
    - click
    - python >=2.7

test:
  requires:
    - pip
  imports:
    - pycondor
    - pycondor.job
    - pycondor.dagman
    - pycondor.utils
    - pycondor.basenode
    - pycondor.cli
    - pycondor.visualize
    - pycondor.compatibility
  commands:
    # check requirements
    - python -m pip check
    # check entry points
    - pycondor -h

about:
  home: https://github.com/pycondor/pycondor
  dev_url: https://github.com/pycondor/pycondor.git
  doc_url: https://pycondor.readthedocs.io/
  license: MIT
  license_file: LICENSE
  summary: Python utility for HTCondor
  description: |
    PyCondor (Python HTCondor) is a tool to help build and submit workflows to
    HTCondor in a straight-forward manner with minimal hassle.

extra:
  recipe-maintainers:
    - duncanmmacleod
    - GregoryAshton
    - jodergrosse
    - jrbourbeau
