{% set name = "PyCondor" %}
{% set version = "0.5.0" %}
{% set sha256 = "9cf8b54159fe3a654d71ffc815840c642f3bd0c89edb401952d6b9092abf0cc2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    # fix of import from collections
    - collections.patch

build:
  noarch: python
  number: 1
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"
  entry_points:
    - pycondor = pycondor.cli:cli


requirements:
  build:
    - python >=2.7
    - pip
  run:
    - python >=2.7
    - click

test:
  imports:
    - pycondor
    - pycondor.job
    - pycondor.dagman
    - pycondor.utils
    - pycondor.basenode
    - pycondor.cli
    - pycondor.visualize
    - pycondor.compatibility
  commands:
    - pycondor -h

about:
  home: https://github.com/jrbourbeau/pycondor
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Python utility for HTCondor'
  description: |
    PyCondor (Python HTCondor) is a tool to help build and submit workflows to
    HTCondor in a straight-forward manner with minimal hassle.
  doc_url: https://jrbourbeau.github.io/pycondor/
  dev_url: https://github.com/jrbourbeau/pycondor

extra:
  recipe-maintainers:
    - jrbourbeau
