{% set name = "PyCondor" %}
{% set version = "0.6.0" %}
{% set sha256 = "3424b8f51ac63a18d3c12e1dae5316a5faa0c1dd1606bb6c1f524df5c031fcb5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    # fix of import from collections
    - collections.patch

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv
  entry_points:
    - pycondor = pycondor.cli:cli


requirements:
  host:
    - python >=2.7
    - pip
  run:
    - python >=2.7
    - click

test:
  imports:
    - pycondor
    - pycondor.job
    - pycondor.dagman
    - pycondor.utils
    - pycondor.basenode
    - pycondor.cli
    - pycondor.visualize
    - pycondor.compatibility
  commands:
    - pycondor -h

about:
  home: https://github.com/jrbourbeau/pycondor
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Python utility for HTCondor
  description: |
    PyCondor (Python HTCondor) is a tool to help build and submit workflows to
    HTCondor in a straight-forward manner with minimal hassle.
  doc_url: https://jrbourbeau.github.io/pycondor/
  dev_url: https://github.com/jrbourbeau/pycondor

extra:
  recipe-maintainers:
    - duncanmmacleod
    - jrbourbeau
