travis:
  secure:
    BINSTAR_TOKEN: LFUWWSiz1h8YWw7CrHDQP6HgHD7ANH7zXHIH9DeqCNeQsnkWtnPU/4ZS6/yZoLAJ4mrOu2+QAm8wjyzAp5sgZ4XfsHv3+gYmHhpqeXDsffTjwv2Y1D/O3Fn+HnxCgKIm+6l+auZe6hRZxPQC8ZfcMPl9p76Nxz3uFiFwzjnZXatlwDQLEnsuJlo/e9Z9s7E5G7vWS+a2eOxyIE3vUIaFfd+hzI5Y+gMRkPkm1o0iehG9N1Qf5SoDeLB4IqHZyQwQ4AVhMV92p3v08XlUtz0fCCfZUhHo54tvhmvoKW8q7IjQlxWyKmVhvrxGBwob5T5GbJWUkXhUEV2Y4Rlqv41dRCPDv9NZKL7My8vO0Q5IM/qbTPvn75Pdi6aOfWy4mc4ZUfkwpFR14tmH9PLUQDK/DosZzqoHkgxg+1v622DvnNepePrazti7oXOTrKOMZ48DR/tMm9dwbkdWTc0QKrZyqDaoc00hFYlNoNLnlD8hVuRMYxwqRTWmFBQGiBz6R/a9cTJnr/ibVg4z10uRcI41eM2tI2Uw05vnfnEqiorCE4TnPhAml+jkhRpD7aC4JFecTttpck6fBKRArsXpRipYWxemp/vy636K9elyDWlEkPX87PRp2R/Ldp0ZzEpxNQP/60DCVJedyu/ZffGTRVZDgZU7K9eSf6Zttl7OdFr2+Ow=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
