travis:
  secure:
    BINSTAR_TOKEN: aX5a7JBdzcw9WBo+AvME9L+xh+5wye6psvjjtVi9ZE61BfsntlrkK7RzhcOhgAqdtpHS6IGYoI0HfYiOAopaQJDab5bwZWIr6qcGAJfx4tJ5Ci0KCrSvBv51Jy9OihveGb1VZpAYwUbYql0NMA8PVizchE8Ts5WaBHetT+MriJd/HGcLSkA/vggLmwNQhxntL1N0zWOFkpFGO9dAkjNJBk5gVDMGcvJFo4LbQnEXeJz0QmMbK5G4p9Gj1EyC7SUFvYJkFYmXvwHYI1AiALTJ+/EAKyaST94YOBpy1IdeQ4fV8Qc9wJmHErLHKbGSO25ELvU9IkqnADr5zjlCO0iICohURpYsS4+ofvJzoWlDq8RvHV/hTt9roxh/QKBHJLZPAOdZTVyAtkoKBDP9vlD1/Gne4VdOQvix4BKwzHkgqAMBxuTfWfTV5s4eh4m5mZEYbWs0PzRNI25J+A39nnMaAi2rcqIEZ2pwoLwIu3XzAddM6NRCkxAWkaI9V3Q8JKH7k/4riU3V/hRstK3uMVw4rSYvrdlCRVgIp3mlMId2By5uTU5k8vLuoLiai039t9lr+6I7Zmtbhft+nL/kcmqUtj1G1CC09WdFRKKg6bf561yL8uPuYSYEbDMfF4NmrejmG4zFDbEKHfzgbhvW6V9rltq5kqOj7aYA0JaxUmeQRtw=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
